export const COTI_TESTNET_CHAIN_ID = 7082400 as const;
export const COTI_MAINNET_CHAIN_ID = 2632500 as const;
export const SUPPORTED_CHAIN_IDS = [
  COTI_MAINNET_CHAIN_ID,
  COTI_TESTNET_CHAIN_ID,
] as const;
export const DEFAULT_CHAIN_ID = COTI_TESTNET_CHAIN_ID;
